Disable -Wunused-parameter in deqp.
external/deqp-deps/glslang/glslang/MachineIndependent/localintermediate.h:395:30:
error: unused parameter 's' [-Werror,-Wunused-parameter]
    void setSource(EShSource s) { assert(s == EShSourceGlsl); }

Bug: 149839606
Test: build.
Change-Id: I4abc1d7da439aa262e2b7fc60972f2d736d66009
Merged-In: I4abc1d7da439aa262e2b7fc60972f2d736d66009
(cherry picked from commit 1572042467bbdcc81f68b9557879233336dee2ea)